---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    component: homework
    app: alpine
  namespace: default
spec:
  containers:
  - name: alpine
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c", "apk update && apk add bash curl wget jq kubectl helm inetutils-telnet rsync ansible ansible-lint yamllint golangci-lint gitlint jq yq openssl"]
    resources:
      limits:
        memory: "256Mi"
        cpu: "1000m"
    volumeMounts:
    - mountPath: /data
      name: csi-s3
  restartPolicy: Never
  volumes:
    - name: csi-s3
      persistentVolumeClaim:
        claimName: csi-s3-pvc
        readOnly: false
