apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: default
stringData:
  accessKeyID: "YCAJENew8pXmv3i29jwIaupdV"
  secretAccessKey: "YCOpVhF6QnbnKmlIauXTu5**********"
  endpoint: https://storage.yandexcloud.net
  region: "ru-central1"
  