apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-distroless
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: kyos0109/nginx-distroless
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx
          mountPath: /data/nginx
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:
      - name: nginx
        emptyDir: {}
