---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: vault
  labels:
    name: otus  
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'otus'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'otus/cred'
    vault.hashicorp.com/service: 'http://vault.vault.svc.cluster.local:8200'
spec:
  containers:
  - name: test
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c", "apk update && apk add bash curl wget jq kubectl helm inetutils-telnet rsync ansible ansible-lint yamllint golangci-lint gitlint jq yq openssl"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  serviceAccount: vault-auth
      